sonar.projectKey=aelfric_tabroom-fakeballot
sonar.organization=aelfric


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=tabroom-fakeballot
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=src/tabroom.css,src/fonts.css,**/*.woff,**/*.woff2,**/*.eot,**/*.ttf,**/*.png

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8