/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const AboutLazyRouteImport = createFileRoute('/about')()
const CongressLazyRouteImport = createFileRoute('/congress')()
const DebateLazyRouteImport = createFileRoute('/debate')()
const SpeechLazyRouteImport = createFileRoute('/speech')()
const SpeechFeedbackLazyRouteImport = createFileRoute('/speech-feedback')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const CongressLazyRoute = CongressLazyRouteImport.update({
  id: '/congress',
  path: '/congress',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/congress.lazy').then((d) => d.Route))
const DebateLazyRoute = DebateLazyRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/debate.lazy').then((d) => d.Route))
const SpeechLazyRoute = SpeechLazyRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/speech.lazy').then((d) => d.Route))
const SpeechFeedbackLazyRoute = SpeechFeedbackLazyRouteImport.update({
  id: '/speech-feedback',
  path: '/speech-feedback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/speech-feedback.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/congress': typeof CongressLazyRoute
  '/debate': typeof DebateLazyRoute
  '/speech': typeof SpeechLazyRoute
  '/speech-feedback': typeof SpeechFeedbackLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/congress': typeof CongressLazyRoute
  '/debate': typeof DebateLazyRoute
  '/speech': typeof SpeechLazyRoute
  '/speech-feedback': typeof SpeechFeedbackLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/congress': typeof CongressLazyRoute
  '/debate': typeof DebateLazyRoute
  '/speech': typeof SpeechLazyRoute
  '/speech-feedback': typeof SpeechFeedbackLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/congress' | '/debate' | '/speech' | '/speech-feedback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/congress' | '/debate' | '/speech' | '/speech-feedback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/congress'
    | '/debate'
    | '/speech'
    | '/speech-feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  CongressLazyRoute: typeof CongressLazyRoute
  DebateLazyRoute: typeof DebateLazyRoute
  SpeechLazyRoute: typeof SpeechLazyRoute
  SpeechFeedbackLazyRoute: typeof SpeechFeedbackLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congress': {
      id: '/congress'
      path: '/congress'
      fullPath: '/congress'
      preLoaderRoute: typeof CongressLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate': {
      id: '/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof DebateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech': {
      id: '/speech'
      path: '/speech'
      fullPath: '/speech'
      preLoaderRoute: typeof SpeechLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech-feedback': {
      id: '/speech-feedback'
      path: '/speech-feedback'
      fullPath: '/speech-feedback'
      preLoaderRoute: typeof SpeechFeedbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  CongressLazyRoute: CongressLazyRoute,
  DebateLazyRoute: DebateLazyRoute,
  SpeechLazyRoute: SpeechLazyRoute,
  SpeechFeedbackLazyRoute: SpeechFeedbackLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
